from enum import Enum, auto

class Estado(Enum):
    IDLE = auto()
    WALK = auto()
    RUN = auto()
    DASH = auto()
    JUMP = auto()
    FALL = auto()
    LAND = auto()
    ATTACK_LIGHT = auto()
    ATTACK_HEAVY = auto()
    ATTACK_AIR = auto()
    SPECIAL = auto()
    ULTIMATE = auto()
    BLOCK = auto()
    PARRY = auto()
    GRAB = auto()
    HITSTUN = auto()
    BLOCKSTUN = auto()
    KNOCKDOWN = auto()
    GET_UP = auto()
    RELEASE = auto()
    EXHAUSTED = auto()
    VICTORY = auto()
    DEFEAT = auto()

class Fluxo(Enum):
    TITLE = auto()
    SELECT = auto()
    INTRO = auto()
    FIGHT = auto()
    KO = auto()
    VICTORY = auto()
