"""Export the preserved Python reference into editable cross-engine JSON and atlases."""
import os
os.environ.setdefault('SDL_VIDEODRIVER','dummy')
os.environ.setdefault('SDL_AUDIODRIVER','dummy')
import sys
import json
import shutil
from pathlib import Path
from dataclasses import asdict
ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/'Fighting-Eclipse-Reformulado'/'Fighting'))
import pygame
from seu_personagem import PERFIS, criar_personagem
from catalog import KITS
from states import Estado
from animation import sprite

def write(path,value):
    path.parent.mkdir(parents=True,exist_ok=True)
    path.write_text(json.dumps(value,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')

def export():
    pygame.init();pygame.display.set_mode((1,1))
    content=ROOT/'content'
    for profile in PERFIS:
        p=criar_personagem(profile.id,400);kit=asdict(KITS[profile.id])
        moves={}
        for key,move in p.moves.items():
            data=asdict(move);data['estado']=move.estado.name
            data.update(command=key,hitstun=.34,blockstun=.16,knockdown=.65,
                        animation=move.estado.name,sound='heavy' if move.queda else 'hit',
                        cancel_on_hit=key in ('light','heavy','air'),
                        hitboxes=[{'time':t,'reach':move.alcance,'y':20,'height':profile.altura-30} for t in move.hits])
            moves[key]=data
        write(content/'moves'/f'{profile.id}.json',moves)
        write(content/'forms'/f'{profile.id}.json',kit.pop('forms'))
        write(content/'characters'/f'{profile.id}.json',{'profile':asdict(profile),'kit':kit,
              'moves':f'moves/{profile.id}.json','forms':f'forms/{profile.id}.json',
              'sprite':f'res://assets/fighters/{profile.id}.png','released_sprite':f'res://assets/fighters/{profile.id}_released.png',
              'animation_states':[state.name for state in Estado]})
        for released in (False,True):
            sheet=pygame.Surface((2400,len(Estado)*230),pygame.SRCALPHA)
            for row,state in enumerate(Estado):
                for frame in range(8):sheet.blit(sprite(profile.id,state,frame,released,1),(frame*300,row*230))
            target=ROOT/'godot/assets/fighters'/f'{profile.id}{"_released" if released else ""}.png'
            target.parent.mkdir(parents=True,exist_ok=True);pygame.image.save(sheet,str(target))
    for key,name,color in [('soul_society','Soul Society',[.10,.18,.26]),('karakura','Karakura',[.12,.12,.24]),('hueco_mundo','Hueco Mundo',[.15,.20,.24])]:
        write(content/'arenas'/f'{key}.json',{'id':key,'name':name,'color':color,'width':1700,'floor':580})
    write(content/'palettes/default.json',{'names':['Original','Âmbar','Violeta','Gelo'],'colors':[[1,1,1],[1,.72,.40],[.78,.55,1],[.55,1,1]]})
    write(content/'effects/default.json',{'hitstop':.045,'heavy_hitstop':.09,'flash':.13,'shake':11})
    write(content/'audio/default.json',{'hit':'res://assets/audio/hit.wav','heavy':'res://assets/audio/heavy.wav','release':'res://assets/audio/release.wav','menu':'res://assets/audio/menu.wav'})
    write(content/'manifest.json',{'version':1,'characters':[p.id for p in PERFIS],'arenas':['soul_society','karakura','hueco_mundo']})
    # Test vectors are generated by the original simulation, not hand-copied expectations.
    cases=[]
    for profile in PERFIS:
        for command in ('walk','jump','dash','release'):
            p=criar_personagem(profile.id,400);target=criar_personagem('vastor',1400)
            p.reiatsu=p.reiatsu_maximo
            if command=='walk':p.mover(1)
            else:p.executar(command)
            for _ in range(60):p.atualizar(1/120,target)
            cases.append({'id':profile.id,'command':command,'steps':60,'x':p.x,'y':p.y,'energy':p.reiatsu,'stamina':p.stamina,'state':p.estado_atual.name})
    write(content/'reference.json',cases)
    from audio import Audio
    audio=Audio();target=ROOT/'godot/assets/audio';target.mkdir(parents=True,exist_ok=True)
    import wave,math,struct
    for name,sound in audio.sounds.items():
        with wave.open(str(target/f'{name}.wav'),'wb') as out:
            out.setnchannels(pygame.mixer.get_init()[2]);out.setsampwidth(2);out.setframerate(44100);out.writeframes(sound.get_raw())
    # Original, quiet ambient loop with a fade at each end.
    with wave.open(str(target/'menu.wav'),'wb') as out:
        out.setnchannels(1);out.setsampwidth(2);out.setframerate(22050)
        samples=[]
        for i in range(22050*8):
            t=i/22050;fade=min(1,t,8-t)
            v=sum(math.sin(2*math.pi*f*t) for f in (110,165,220))*650*fade
            samples.append(struct.pack('<h',int(v)))
        out.writeframes(b''.join(samples))
    stage();pygame.quit();print('Content, sprites, sounds and 20 reference cases exported.')

def stage():
    shutil.copytree(ROOT/'content',ROOT/'godot/content',dirs_exist_ok=True)

if __name__=='__main__':
    stage() if '--stage' in sys.argv else export()
